### PR TITLE
Admin- Departments View

### PR DESCRIPTION
**Pull request by sugamshres**
A new user control is displayed which contains the Departments and its abbreviations textbox, and the two buttons, once the Departments button is selected on the MainWindow.

### CODE REVIEW

**Review by mxn46170 — COMMENTED** [review]
Everything looks good, one small thing: please move the hard-coded values into the app.xaml of the project you worked on.

**Comment by sugamshres** [comment]
@mxn46170  The hard coded values have been moved to the app.xaml file in the latest commit.

**Review by mxn46170 — COMMENTED** [review]
The App.xaml file for the Professor module is showing here (it shouldn't). Please add the app.xaml for the Administration module instead.

Please revert your changes for the SchoolSetupView, it is showing up in this pull request.

You're missing the xaml.cs file for you new Departments View

**Review by mxn46170 — APPROVED** [review]
looks good

**Pull request closed without merging**
